#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=/usr/sbin:$PATH
export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_PLATFORMTHEME="qt5ct"
export QT_PLATFORM_PLUGIN="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
